name: CI to DockerHub

on :
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    APP_NAME: treehole_next

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Docker Layer
              uses: actions/cache@master
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                    ${{ runner.os }}-buildx-

            - name: Checkout
              uses: actions/checkout@master

            - name: Set up QEMU
              uses: docker/setup-qemu-action@master

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@master

            - name: Login to DockerHub
              uses: docker/login-action@master
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@master
              with:
                context: .
#                builder: ${{ secrets.DOCKER_BUILDER }}
                push: true
                tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest
                  ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:main
                cache-from: type=local,src=/tmp/.buildx-cache
                cache-to: type=local,dest=/tmp/.buildx-cache